from pydantic import BaseModel, Field, field_validator


class Evidence(BaseModel):
    """
    Evidence supporting the remediation plan.
    """

    source: str = Field(
        ...,
        description=(
            "Evidence source such as logs, metrics, runbook, "
            "or historical."
        ),
    )

    detail: str = Field(
        ...,
        min_length=1,
        description="Specific evidence supporting the plan.",
    )


class RecommendedAction(BaseModel):
    """
    A proposed remediation action.

    Actions are proposals only. They must never be executed directly
    by the remediation agent.
    """

    action: str = Field(
        ...,
        min_length=1,
        description="Specific remediation action to propose.",
    )

    risk: str = Field(
        ...,
        min_length=1,
        description="Operational risk associated with the action.",
    )

    requires_approval: bool = Field(
        default=True,
        description=(
            "Human approval is required before this action can "
            "be executed."
        ),
    )

    @field_validator("requires_approval")
    @classmethod
    def approval_must_be_required(
        cls,
        value: bool,
    ) -> bool:
        """
        Enforce the human approval boundary.

        Remediation actions generated by this application must always
        require human approval.
        """

        if value is not True:
            raise ValueError(
                "All remediation actions must require human approval."
            )

        return value


class ServiceNowUpdate(BaseModel):
    """
    Content prepared for a future ServiceNow update.

    This model contains data only. It does not perform the update.
    """

    short_description: str = Field(
        ...,
        min_length=1,
        description="Short ServiceNow incident description.",
    )

    severity: str = Field(
        ...,
        min_length=1,
        description="ServiceNow incident severity.",
    )

    work_notes: str = Field(
        ...,
        min_length=1,
        description=(
            "AI-generated investigation and remediation summary "
            "to be added to ServiceNow work notes."
        ),
    )


class RemediationPlan(BaseModel):
    """
    Structured remediation plan produced by the remediation agent.
    """

    incident_summary: str = Field(
        ...,
        min_length=1,
        description="Concise summary of the incident.",
    )

    likely_root_cause: str = Field(
        ...,
        min_length=1,
        description="Root cause identified during diagnosis.",
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Diagnosis confidence from 0 to 1.",
    )

    evidence: list[Evidence] = Field(
        default_factory=list,
        description="Evidence supporting the remediation plan.",
    )

    recommended_actions: list[RecommendedAction] = Field(
        ...,
        min_length=1,
        description="Proposed remediation actions.",
    )

    rollback_plan: str = Field(
        ...,
        min_length=1,
        description=(
            "Steps for safely reversing the remediation if "
            "the change causes problems."
        ),
    )

    servicenow_update: ServiceNowUpdate = Field(
        ...,
        description=(
            "Structured content prepared for a future ServiceNow "
            "update."
        ),
    )